#!/usr/bin/env bash
# Tool Name :- IP-Tracer
# Author :- venz.db
# Date :- 10/07/2024

if [ -d /data/data/com.termux/files/usr/share ];then
  cd /data/data/com.termux/files/usr/share/IP-Tracer
  exec bash trace $@
elif [ -d /usr/share ];then
  cd /usr/share/IP-Tracer
  exec bash trace $@
fi
